#!/usr/bin/perl

use warnings;
use strict;

if (($#ARGV + 1) == 0) {
  die "Usage:\n\tnp Post Name\n";
}

my $post_title = join(' ', @ARGV);
my $post_file = join(' ', @ARGV);
$post_file =~ s/[^A-Za-z0-9\s]//g;
$post_file =~ s/\s+/-/g;
my $post_yaml = "---\nlayout: post\ntitle: $post_title\nexcerpt_separator: <!--more-->\n---\n\n";

my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime();

my $file_name = sprintf("%04d-%02d-%02d-%s.md", ($year + 1900), ($mon + 1), $mday, $post_file);

open(FILE, "+>", $file_name);
print FILE $post_yaml;
close(FILE);


